### ISSUE TITLE
TV logos now too large

### ISSUE THREAD

**Issue by dgilbert2** [speculatrix/tvh_epg#13]
Following what I believe  is a recent change to the mainstream browsers (on Windows), i.e. Chrome, Firefox, Microsoft Edge, TVLogos are now massive, see below.

My tvh_epg has not changed and I've tried browsers on another PC and the result is the same. However, it still displays correctly on my iPhone / iPad.

![image](https://user-images.githubusercontent.com/28821175/106644796-79971e00-6583-11eb-89fb-e4a8d7f40305.png)

**Comment by dgilbert2** [comment]
I've done some digging into this and it appears from what I can see, that Windows browsers are now ignoring the img height% command. So, by adding specific height and width it reduces the size as it should do, which I've tested on Windows Chrome, Firefox and Edge as well as iOS Safari. The two lines I've changed in tvh_epg to get my system working as it should, are detailed below. Hope this helps.

```
Line 517
WAS '<img height="12%%" src="%s" /></td>' %
NOW '<img height="80" width="140" src="%s" /></td>' %

Line 719
WAS '<img height="12%%" src="%s" /></td>' %
NOW '<img height="80" width="140" src="%s" /></td>' %
```

Screen now looks like;

![image](https://user-images.githubusercontent.com/28821175/106746920-1bb61500-661b-11eb-9524-81fb18ffadf3.png)

**Comment by speculatrix** [comment]
Hi,
sorry for delay in fixing this, I just pushed a commit.
pull down the latest version and if you go into settings you can now set a size, about 64 h x 80 w seems ok

**Comment by speculatrix** [comment]
let me know what you think if this solves the problem.

**Comment by dgilbert2** [comment]
Thanks, this resolves the logo size problem and I like being able to set own w & h values.

I still have a problem though with lines 566 & 569, browser.close(), ie I need to # these out otherwise I get errors;

AttributeError: 'ServiceBrowser' object has no attribute 'close'
      args = ("'ServiceBrowser' object has no attribute 'close'",)
      with_traceback = <built-in method with_traceback of AttributeError object>

BTW, no issues with fix #12 , as long as I set to "plain".
